#!/usr/bin/env bash
set -Eeuo pipefail
SCRIPT_VERSION="1.0.0"
INSTALL_PREFIX="${INSTALL_PREFIX:-/opt/astrbot}"
PROJECT_DIR="${PROJECT_DIR:-$INSTALL_PREFIX/AstrBot-Deploy}"
DATA_DIR="${DATA_DIR:-$INSTALL_PREFIX/data}"
COMPOSE_DIR="${COMPOSE_DIR:-$INSTALL_PREFIX/compose}"
NAPCAT_BASE_DIR="${NAPCAT_BASE_DIR:-$INSTALL_PREFIX/napcat}"
BACKUP_DIR="${BACKUP_DIR:-$INSTALL_PREFIX/backups}"
LOG_DIR="${LOG_DIR:-$INSTALL_PREFIX/logs}"
STATE_FILE="${STATE_FILE:-$INSTALL_PREFIX/.env}"
DEPLOY_INFO_FILE="${DEPLOY_INFO_FILE:-$INSTALL_PREFIX/deploy_info.txt}"
NAPCAT_INDEX_FILE="${NAPCAT_INDEX_FILE:-$INSTALL_PREFIX/napcat_index.tsv}"
NETWORK_NAME="${NETWORK_NAME:-astrbot_network}"
ASTRBOT_IMAGE="${ASTRBOT_IMAGE:-soulter/astrbot:latest}"
NAPCAT_IMAGE="${NAPCAT_IMAGE:-mlikiowa/napcat-docker:latest}"
ASTRBOT_CONTAINER="${ASTRBOT_CONTAINER:-astrbot}"
ASTRBOT_USERNAME="${ASTRBOT_USERNAME:-astrbot}"
ASTRBOT_INTERNAL_WEB_PORT=6185
ASTRBOT_INTERNAL_WS_PORT=6199
NAPCAT_INTERNAL_WEBUI_PORT=6099
NAPCAT_INTERNAL_WS_PORT=3001
NAPCAT_INTERNAL_HTTP_PORT=3000
DEFAULT_TIMEZONE="${TZ:-Asia/Shanghai}"
